export const styles = {
  root: {
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: '#ffffff',
    color: '#374151',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '0 1rem'
  },
  container: {
    backgroundColor: '#fff',
    maxWidth: '1200px',
    width: '100%',
    padding: '0 1.5rem',
    flexGrow: 1,
    margin: '2rem 0 0 0',
  },
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '63px',
    backgroundColor: '#ffffff',
    borderBottom: '1px solid #e5e7eb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 0.3rem 0 0.8rem',
    zIndex: 1000,
    boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
  },
  logo: {
    fontWeight: 700,
    fontSize: '1.5rem',
    color: '#111827',
    letterSpacing: '0.05em',
    userSelect: 'none',
  },
  nav: {
    WebkitTapHighlightColor: 'transparent',
    display: 'flex',
    gap: '0.5rem'
  },
  navButton: (active) => ({
    background: active ? '#000' : 'none',
    border: active ? '1px solid #fff' : '1px solid #000',
    fontWeight: 600,
    fontSize: '1rem',
    color: active ? '#fff' : '#000',
    cursor: 'pointer',
    padding: '0.5rem 0.75rem',
    borderRadius: '0.75rem',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  }),
  form: {
    width: '85%',
    padding: '2rem 2rem 2.5rem',
    borderRadius: '0.75rem',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
    margin: '5rem 0 0 -0.5rem',
    border: '1px solid #e5e7eb',
  },
  formHeading: {
    fontWeight: 700,
    fontSize: '2rem',
    margin: 0,
    color: '#111827',
  },
  label: {
    fontWeight: 700,
    fontSize: '0.9rem',
    color: '#6b7280',
    marginBottom: '0.3rem',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '0.6rem 0.75rem',
    fontSize: '1rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.75rem',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    fontFamily: 'inherit',
    color: '#374151',
    outlineOffset: '2px',
    boxSizing: 'border-box',
  },
  inputFocus: {
    borderColor: '#3b82f6',
    boxShadow: '0 0 5px #3b82f6',
  },
  submitButton: {
    WebkitTapHighlightColor: 'transparent',
    backgroundColor: '#000',
    color: '#fff',
    fontWeight: 700,
    fontSize: '1rem',
    padding: '0.75rem',
    border: 'none',
    borderRadius: '0.75rem',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  submitButtonHover: {
    boxShadow: '0 4px 80px rgba(0,0,0,0.4)',
  },
  dashboard: {
    marginTop: '3rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  },
  greeting: {
    fontWeight: 800,
    fontSize: '2rem',
    color: '#111827',
    marginBottom: '-.7rem',
    userSelect: 'none',
  },
  passwordsList: {
    marginTop: '1.25rem',
    display: 'flex',
    flexWrap: 'wrap',
    gridTemplateColumns: '1fr',
    gap: '1.25rem',
    marginBottom: '2rem',
  },

  passwordCard: {
    border: '1px solid #d1d5db',
    backgroundColor: '#fff',
    borderRadius: '0.75rem',
    boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
    padding: '1rem 1.5rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'default',
    maxWidth: '260px',
  },
  passwordCardHover: {
    boxShadow: '0 6px 15px rgba(0,0,0,0.1)',
    transform: 'translateY(-2px)',
  },
  passwordInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    maxWidth: '70%',
    overflowWrap: 'anywhere',
  },
  site: {
    fontWeight: 700,
    fontSize: '1.125rem',
    color: '#111827',
  },
  usernameText: {
    fontSize: '0.9rem',
    color: '#6b7280',
  },
  passwordText: {
    fontFamily: 'monospace',
    fontSize: '1rem',
    color: '#6366f1',
    letterSpacing: '0.05em',
  },
  errorText: {
    color: '#dc2626',
    fontSize: '0.875rem',
    marginTop: '-0.75rem',
  },
  footer: {
    textAlign: 'center',
    padding: '1rem 0',
    fontSize: '0.85rem',
    color: '#9ca3af',
  },
};